name: msgpack
description: MsgPack for Dart
version: 0.5.0
authors:
- Kenneth Endfinger <kaendfinger@gmail.com>
- Dan Ellis <dan@danellis.me>
homepage: https://github.com/DirectMyFile/msgpack.dart
dev_dependencies:
  test: ">=0.12.13"
